# Generated by Django 5.2.12 on 2026-05-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='investigations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
