# Generated by Django 5.2.12 on 2026-05-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_medicalhistory_investigations'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='bp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='chest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='cns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='cvs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='pa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='pulse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='spo2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
