# Generated by Django 5.2.12 on 2026-05-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_medicalhistory_bp_medicalhistory_chest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentlogentry',
            name='department',
            field=models.CharField(choices=[('opd', 'OPD'), ('intimation', 'Intimation'), ('query', 'Query'), ('uploading', 'Uploading'), ('billing', 'Billing'), ('nursing', 'Nursing'), ('doctor', 'Doctor'), ('notes', 'Notes'), ('quality_analyst', 'Quality Analysis'), ('medical_officer', 'Medical Officer')], max_length=20),
        ),
    ]
