# Generated by Django 5.2.12 on 2026-05-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_departmentlogentry_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='SANGI HOSPITAL', max_length=255)),
                ('branch_name', models.CharField(default='Lakshmi Nagar Branch', max_length=255)),
                ('address', models.TextField(default='Lakshmi Nagar, Mathura, Uttar Pradesh - 281004')),
                ('phone', models.CharField(default='+91-9717444531 / +91-9717444532', max_length=150)),
                ('email', models.EmailField(default='laxminagar@sangihospital.com', max_length=254)),
                ('website', models.URLField(default='https://www.sangihospital.com')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
