# Generated by Django 5.2.12 on 2026-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_hospitalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsettings',
            name='branch',
            field=models.CharField(choices=[('LNM', 'Laxmi Nagar'), ('RYM', 'Raya')], default='LNM', max_length=3, unique=True),
        ),
    ]
