# Generated by Django 5.2.12 on 2026-05-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_alter_service_svccode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentlogentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='hodreview',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='hodreview',
            name='reviewed_by',
        ),
        migrations.DeleteModel(
            name='HospitalSettings',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='patient',
        ),
        migrations.DeleteModel(
            name='MedicineMaster',
        ),
        migrations.RemoveField(
            model_name='pharmacyrecord',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='pharmacyrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pharmacyrecord',
            name='patient',
        ),
        migrations.DeleteModel(
            name='ReportMaster',
        ),
        migrations.DeleteModel(
            name='ServiceMaster',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='patient',
        ),
        migrations.DeleteModel(
            name='DepartmentLogEntry',
        ),
        migrations.DeleteModel(
            name='DischargeSummary',
        ),
        migrations.DeleteModel(
            name='HODReview',
        ),
        migrations.DeleteModel(
            name='LabReport',
        ),
        migrations.DeleteModel(
            name='PharmacyRecord',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
