# Generated by Django 5.2.12 on 2026-05-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_billing_onetoone_task_admission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'ordering': ['-admNo']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['svcDate', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='billing',
            name='billing_print_idx',
        ),
        migrations.RemoveIndex(
            model_name='billing',
            name='billing_admission_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patient_branch_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patient_paymode_idx',
        ),
        migrations.RenameIndex(
            model_name='admission',
            new_name='patients_ad_patient_04acf7_idx',
            old_name='admission_patient_admno_idx',
        ),
        migrations.RenameIndex(
            model_name='admission',
            new_name='patients_ad_payMode_56d1bb_idx',
            old_name='admission_paymode_idx',
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['admission', 'svcDate'], name='patients_se_admissi_4be3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['pricing_applied'], name='patients_se_pricing_85bf86_idx'),
        ),
    ]
