# Generated by Django 5.2.12 on 2026-05-10 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0018_remove_departmentlogentry_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('NORMAL', 'Normal'), ('LAMA', 'LAMA'), ('REFERRED', 'Referred'), ('DEATH', 'Death'), ('DOPR', 'dopr')], max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_summary', to='patients.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(blank=True, max_length=100)),
                ('report_category', models.CharField(blank=True, max_length=50)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('ordered_by', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('modality_details', models.JSONField(blank=True, default=dict)),
                ('table_data', models.JSONField(default=list)),
                ('text_data', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='patients.admission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.CharField(max_length=50)),
                ('medicine_name', models.CharField(max_length=255)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_records', to='patients.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_records', to='patients.patient')),
            ],
        ),
    ]
