# Generated by Django 5.2.12 on 2026-05-15 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_alter_admission_options_alter_service_options_and_more'),
        ('tasks', '0002_task_admission_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_patient_359bd3_idx',
            old_name='task_patient_assignee_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='admission',
            field=models.ForeignKey(blank=True, help_text='Specific admission this task is for. If null, defaults to latest active admission.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='patients.admission'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['admission', 'status'], name='tasks_task_admissi_fe074f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='tasks_task_assigne_b3b2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='tasks_task_created_be1ba2_idx'),
        ),
    ]
