# Generated by Django 5.2.12 on 2026-05-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='LNM', max_length=10, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('uhid_prefix', models.CharField(default='SHL', max_length=10)),
                ('hospital_name', models.CharField(default='SANGI HOSPITAL', max_length=255)),
                ('branch_name', models.CharField(default='Lakshmi Nagar Branch', max_length=255)),
                ('address', models.TextField(default='Lakshmi Nagar, Mathura, Uttar Pradesh - 281004')),
                ('phone', models.CharField(default='+91-9717444531 / +91-9717444532', max_length=150)),
                ('email', models.EmailField(default='laxminagar@sangihospital.com', max_length=254)),
                ('website', models.URLField(default='https://www.sangihospital.com')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ICU CARE', 'ICU Care'), ('ROOM CHARGE', 'Room Charge'), ('CONSULTANT', 'Consultant'), ('RADIOLOGY', 'Radiology'), ('GENERAL SERVICES', 'General Services')], max_length=50)),
                ('pricing_type', models.CharField(choices=[('CASH', 'Cash'), ('CASHLESS', 'Cashless')], default='CASH', max_length=10)),
                ('description', models.TextField()),
                ('code', models.CharField(blank=True, max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
