# Generated by Django 5.2.12 on 2026-05-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_servicemaster_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicemaster',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctor',
            name='branch',
            field=models.CharField(blank=True, help_text='Leave blank for doctors visible in all branches.', max_length=10, null=True),
        ),
    ]
