# Generated by Django 5.2.12 on 2026-05-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Branch Admin'), ('office_admin', 'Office Admin'), ('receptionist', 'Receptionist'), ('billing', 'Billing'), ('hod', 'HOD'), ('opd', 'OPD'), ('intimation', 'Intimation'), ('query', 'Query'), ('uploading', 'Uploading'), ('nursing', 'Nursing'), ('notes', 'Notes'), ('medical_officer', 'Medical Officer'), ('quality_analyst', 'Quality Analyst'), ('doctor', 'Doctor')], default='receptionist', max_length=20),
        ),
    ]
